### PR TITLE
Results for iMac Pro 10 Core, 64 GB

### PR DESCRIPTION
**Pull request by klaas**
as requested :-)  see https://twitter.com/merowing_/status/946376895788146689

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Oh my gosh! Thanks so much!

**Comment by robertjpayne** [comment]
@klaas just curious, was this how long Xcode took to report the build being completed or for the app to fully launch in the simulator?

Only asking because trying to compare to my Late 2015 iMac and I was hopeful the iMac Pro would show significant gains.

**Comment by klaas** [comment]
Fully launch in the simulator. The CPUs hadn't much load during opening the simulator and launching the app. Pure project compile times are much faster.

**Comment by robertjpayne** [comment]
@klaas ah great! I need to measure simulator launch too, would be nice if these benchmarks included just compile times too for reference 👍

**Pull request merged**
