### PR TITLE
MBP 13 Mid-2017 i5-7360U & Mini Mid-2011 i5-2415M

### PR DESCRIPTION
**Pull request by jokjok**
MBP 13 Mid-2017 I5-7360U

### CODE REVIEW

**Comment by jokjok** [comment]
Regarding tests with MBP 13 Mid-2017 i5-7360U, some notes that may apply to other tests too:

(1) Absolute first time only, machine just rebooted, Fresh Build Time was +25s
(2) If run after reboot, first time Fresh Build Time is + 13s
(3) Closing Xcode between builds results in Fresh Build Time of +5s
(4) Deleting DerivedData folder between builds results in Fresh Build Time of +3s

Regarding (1) & (2), I think something about simulator is somehow cached, even if it is completely closed.
First time you open simulator after boot, Apple logo shows on it. Next times simulator is re-opened, no Apple logo but a spinner instead, and load time faster.

**Review by ashfurrow — APPROVED** [review]
Looks great! Sorry that I forgot about this PR until now. Still good to merge?

**Comment by jokjok** [comment]
Sure ;)

**Comment by ashfurrow** [comment]
Okay! Thanks for your contribution!

**Pull request merged**
