### PR TITLE
i9 9900K Custom Hackintosh

### PR DESCRIPTION
**Pull request by juancazalla**
CPU: i9-9900K 3.6 (Stock)
MB: Asus Maximus XI Hero Wifi
RAM: 32G 3200
Samsung SSD 860
280 water cooler

Build with Xcode 10.1, simulator iPad Air (12.1)

Results:

- Test 1
Fresh 16.89
Incremental 5.45

- Test 2
Fresh 17.21
Incremental 5.32

- Test 3
Fresh 17.16
Incremental 5.21

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Awesome, thanks 🙌

**Comment by ergunkocak** [comment]
🎉  👍

**Comment by brian2694** [comment]
I am currently an Android developer and I want to develop for iOS but I do not have a Mac, so I am in the process of looking for the best option in terms of price and performance.

I have read about Hackintosh and I have a big doubt, have you successfully uploaded applications to the app store from a Hackintosh?

Thanks in advance

**Comment by juancazalla** [comment]
Of course, I can do exactly the same things that I do with my MacBook.

**Pull request merged**
