### PR TITLE
Added 2018 i9 Timings

### LINKED ISSUE #70: MacBook Pro 13"/15" 2018
I'm really wondering how much faster are the newly refreshed MacBook Pros really are. 
Would be nice to have them listed here!

### PR DESCRIPTION
**Pull request by joesanford**
Resolves-ish #70 for 15" MBPs

### CODE REVIEW

**Review by ashfurrow — APPROVED** [review]
Awesome, thanks! Can I just double check that you tested again the new build system? This would be something not enabled by default in the project but would've needed to have been enabled.

**Comment by joesanford** [comment]
Yes, all was tested with the new build system!

**Comment by michael-mckenna** [comment]
4 second incremental build time 😍

**Comment by ashfurrow** [comment]
Amazing, thanks!

**Comment by beeradmoore** [comment]
@joesanford Are you able to re-test after you have [this](https://www.macrumors.com/2018/07/24/2018-macbook-pro-throttling-bug-fix/) patch to see if there is any noticeable change? I am super curious if code compilation would have any thermal issues causing it to slow down, or if that workload is not as heavy as encoding videos.

**Comment by joesanford** [comment]
@beeradmoore after testing, it appears the build time has changed! See https://github.com/ashfurrow/xcode-hardware-performance/pull/76

**Pull request merged**
