### PR TITLE
Add Xcode 11.3.1 measurements

### PR DESCRIPTION
**Pull request by paulz**
with the same machine after upgrading to Catalina and Xcode:

```
Catalina 10.15.3 (19D76)

Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac15,1
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  Boot ROM Version:	232.0.0.0.0
  SMC Version (system):	2.23f11
```

```
sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```

Clean build folder build:
`Build succeeded    2/7/20, 12:14 AM    34.1 seconds`
Incremental build after changing AppDelegate:
`Build succeeded    2/7/20, 12:15 AM    2.8 seconds`

### CODE REVIEW

**Comment by paulz** [comment]
This shows significant improvement from Mojave, Xcode 10 build times on the same hardware:
Clean build 0:40, incremental 0:13 
see https://github.com/ashfurrow/xcode-hardware-performance/pull/94/files

and new Mac Pro 2019 3.2 GHz 16-Core Xeon so not worth it, showing:
Clean build 0:40, incremental 0:06
see https://github.com/ashfurrow/xcode-hardware-performance/pull/111/files

**Comment by beeradmoore** [comment]
@paulz , do all these build times include launching the simulator and waiting until the app has launched?

**Comment by paulz** [comment]
Good point @beeradmoore, I was measuring just build time without the time of launching the simulator app and launching the app.

Now with the 
Launching app adds 10 seconds to the incremental build!
And 6 seconds to the clean build
47 seconds and 12 seconds

Launching app and simulator (iPad Pro iOS 13.3, an iPad Air 2 is only iOS 12.2) adds another 10 seconds
57 seconds and 22 seconds

Also, I am not seeing the Xcode reindexing project after cleaning the build folder, as mentioned here: 
https://github.com/ashfurrow/xcode-hardware-performance/blame/master/Readme.md#L138

**Comment by ashfurrow** [comment]
@paulz Thanks for the contribution! Are the current results in the pull request representative of launching the simulator as well? In other words, is this good to merge?

**Comment by paulz** [comment]
Updated the stats to include simulator launch and app startup. Ready to merge! Thank you for maintaining the metrics, @ashfurrow

**Pull request merged**
