### PR TITLE
Add results for i7 6700k Hackintosh

### PR DESCRIPTION
**Pull request by MrMage**
Timings using Xcode 9.4 with the new build system:

full build: 23/23/22 (+/-0.5 s) = 22s average
incremental: ~7/7/7 (+/-0.2 s) ~ 7s average

Overclocked to 4.5 GHz on all cores.
32 GB DDR4-2400 RAM
1 TB Samsung 970 EVO NVMe SSD (from 2018)

### CODE REVIEW

**Comment by MrMage** [comment]
Scratch the "full build" times; I forgot to let indexing finish. Will update the PR with more accurate times using the new build system in a few minutes.

**Comment by MrMage** [comment]
Also added my rMBP (13" 2018, with the faster quad-core CPU):

27.5/27/26.5
9.8/8.4/10.2

The thermal patch for macOS has been installed already. The tests were run on a "cool" CPU (~50° C, idled for 1-2 minutes before running the test).

In general, it seems like half the time of the full build is spent launching the simulator. On the 2012 model, that fraction is even higher; I guess it is hamstrung by its SATA SSD (~400 MB/s throughput in my case).

**Comment by MrMage** [comment]
Also added my mid 2012 15" rMBP:

66/63/64
14/13/12

Again on a "cool" CPU.

**Review by ashfurrow — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
