### PR TITLE
MacBook Pro 2017 & MacBook Pro 2012

### PR DESCRIPTION
**Pull request by michael-mckenna**

### CODE REVIEW

**Comment by michael-mckenna** [comment]
Note - This is in Xcode 9. Not sure when/how you guys want to add this in. I did not use the new build system when compiling the project.

**Comment by ashfurrow** [comment]
Hmm, yeah we're gonna have to figure that out aren't we? Hmm, well first let me say "thank you" for your contribution 😄 

What do you think about having two tables: one for old Xcode 8 results and another for Xcode 9? The results there can specify if it used the old or new system (they'll all use the old one until I upgrade the project to use the new one 😅). I think the new system mainly improves incremental compiles. I'll add some notes to the readme.

**Comment by michael-mckenna** [comment]
I agree that we should have a second table for Xcode 9. Should we go ahead and start that trend? There can be checkbox to indicate whether the builds were done on the new or old build system.

Additionally I'm not sure if there's a legitimate way to verify build times...but someone reported their MacBook Pro 2015 had a fresh build time of 39 seconds. There's no way that time includes booting up the simulator as well, lol.

**Comment by ashfurrow** [comment]
Pulled this off in #43 – let me know what you think!

Also yeah, I kind of go on the honour system, it's definitely a rough measurement.

**Comment by michael-mckenna** [comment]
@ashfurrow Looks good!

**Pull request merged**
