### PR TITLE
Added another Hackintosh

### PR DESCRIPTION
**Pull request by justMaku**
* i7-4790K 4.00 GHZ, no overclock.
* 32 GB DDR3 memory
* SSD
* Air Cooled

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
I need to get myself a hackintosh 👍

**Review by ashfurrow — APPROVED** [review]
Looks great, thanks!

**Comment by orta** [comment]
Yeah, these hackintosh results are 🌟

**Comment by denizozgur** [comment]
Are you having any problems with xcassets ?
When I add any kind of file (drag txt, png jpeg) xcode goes down in flames

**Comment by brian2694** [comment]
I am currently an Android developer and I want to develop for iOS but I do not have a Mac, so I am in the process of looking for the best option in terms of price and performance.

I have read about Hackintosh and I have a big doubt, have you successfully uploaded applications to the app store from a Hackintosh?

Thanks in advance

**Pull request merged**
