### PR TITLE
Add custom PC to Xcode 9 list

### PR DESCRIPTION
**Pull request by djromero**
[6420](https://browser.geekbench.com/v4/cpu/7096692) single-core score custom built mini-ITX PC:
- i7-8700K 4.70 GHZ slightly overclocked
- 32 GB DDR4 memory
- SSD M.2
- air coolers

### CODE REVIEW

**Comment by ashfurrow** [comment]
Fascinating! Thank you @djromero – this is the first Hackintosh on the list! Can you make the "Custom PC" text into a link to this PR? That way a read can come here and get more details on your PC. After that I would be very happy to merge. Thanks again!

**Review by ashfurrow — APPROVED** [review]

**Comment by michael-mckenna** [comment]
Is this built with a Samsung 960 Evo by chance?

**Comment by djromero** [comment]
Yes, Samsung 960 EVO NVMe M.2.

**Comment by brian2694** [comment]
I am currently an Android developer and I want to develop for iOS but I do not have a Mac, so I am in the process of looking for the best option in terms of price and performance.

I have read about Hackintosh and I have a big doubt, have you successfully uploaded applications to the app store from a Hackintosh?

Thanks in advance

**Pull request merged**
